Kar 3kn
jameshball/osci-render pull request #112
Opened 2022-08-25 15:42 UTC by Kar-3kn

Hi,
    I am Karthikeyan, and this is my first ever open source contribution.

    I have made the following changes
1. Removed Controls from menu bar
2. Prevented translation from being controlled by scroll bar

Please let me know if the changes made are correct and I am happy to work with you.

2022-08-25 16:43 UTC, jameshball commented
Hi Karthikeyan! Thanks so much for the contribution! I'll take a look at this later today or tomorrow :)

2022-08-25 19:43 UTC, jameshball commented
I do a full test of this, but at first glance it looks good, thank you! One thing I noticed and would be good to remove is any references to the Spinner since it's no longer used anywhere or accessible in the interface.

https://github.com/jameshball/osci-render/blob/5da5fcf06861bb8a4ea7257797dc97044a3832d6/src/main/java/sh/ball/gui/controller/MainController.java#L1160

Linked above are the save/load function that saves the value of the slider and loads it (in separate functions) when you save and load an osci-render project.

Since we no longer use the slider, you can remove the field too from MainController and remove any remaining references to it :)

Thank you!

2022-08-26 09:29 UTC, Kar-3kn commented
I have found couple of reference related to Spinner and have removed it. 
Thank you.

2022-08-26 10:00 UTC, jameshball commented
Thanks! I think the field itself (annotated @FXML) at the top of MainController should also be able to be removed :)

2022-08-26 10:49 UTC, Kar-3kn commented
Sorry missed that one.
Done the changes and commited.

2022-08-26 19:49 UTC, jameshball requested changes
Just a few things here and then I expect it to work well and I will test again and merge 😄

2022-08-26 19:49 UTC, jameshball commented on src/main/java/sh/ball/gui/controller/EffectsController.java
> -    translationXTextField.textProperty().addListener(e -> updateTranslation());
This is still required so that when you change the value of the translation text box, the translation effect updates and the object moves. Should work fine if you add this line back :)

2022-08-26 19:49 UTC, jameshball commented on src/main/java/sh/ball/gui/controller/EffectsController.java
> -    translationYTextField.textProperty().addListener(e -> updateTranslation());
Same here, this is required so that the translation in the Y axis updates when the text box changes :)

2022-08-27 14:50 UTC, Kar-3kn commented on src/main/java/sh/ball/gui/controller/EffectsController.java
> -    translationXTextField.textProperty().addListener(e -> updateTranslation());
Done

2022-08-27 14:50 UTC, Kar-3kn commented on src/main/java/sh/ball/gui/controller/EffectsController.java
> -    translationYTextField.textProperty().addListener(e -> updateTranslation());
Done

2022-08-27 15:03 UTC, jameshball approved these changes
Looks great thank you so much! I will update the changelog and version and then merge + release this :)

2022-08-27 15:09 UTC, merged

2022-08-27 15:14 UTC, jameshball commented
@Kar-3kn Thanks so much for your work here and for your first-ever open-source contribution :) 🥳 The release is here: https://github.com/jameshball/osci-render/releases/tag/v1.28.1