Load line art animation from .gpla file rather than from Blender directly
jameshball/osci-render pull request #235
Opened 2024-04-15 20:04 UTC by DJLevel3

Still working on polish and performance, but this works! I need to fix the exporter as well ([find it here](https://github.com/djlevel3/osci-render-gpla)) which is why this is a draft.

2024-04-15 20:43 UTC, jameshball requested changes
Thanks so much for making this, overall it looks great!! Haven't actually run the code yet, and aware you are looking to make it polished and improve performance so will hold off on a full review until later, but just my initial thoughts :)

2024-04-15 20:43 UTC, jameshball commented on Source/PluginProcessor.cpp
> +    if (playHead->getCurrentPosition(currentPositionInfo)) {
[getCurrentPosition](https://docs.juce.com/master/classAudioPlayHead.html#a72788d7f56a3862f3fa352ec572c3f5b) is deprecated. Can you replace this with [getPosition](https://docs.juce.com/master/classAudioPlayHead.html#abe24a517c9f5ffd7d50850f95b683125) instead?

2024-04-15 20:43 UTC, jameshball commented on Source/PluginProcessor.cpp
> +        if ((currentFile >= 0) ? (sounds[currentFile]->parser->isAnimatable) : false) {
Can you simplify this flow? I think this is equivalent to `currentFile >= 0 && sounds[currentFile]->parser->isAnimatable`

2024-04-15 20:43 UTC, jameshball commented on osci-render.jucer
> -              addUsingNamespaceToJuceHeader="0" displaySplashScreen="0" jucerFormatVersion="1"
This needs to be disabled - you can disable the splash screen (since it's GPL) by following this post here https://forum.juce.com/t/how-to-disable-splash-screen-for-open-source-projects-in-juce-6/51256/8

2024-04-15 20:43 UTC, jameshball commented on Source/gpla/LineArtParser.cpp
To avoid duplication, can you use this file in the ObjectServer or vice versa? Currently this is nearly exactly the same as the logic there and if we needed to update it, both would need changing.

2024-04-15 23:47 UTC, DJLevel3 commented on osci-render.jucer
> -              addUsingNamespaceToJuceHeader="0" displaySplashScreen="0" jucerFormatVersion="1"
I didn't know how to do that when I was developing honestly, I'll update that on my end. Thanks for pointing this out!

2024-04-15 23:48 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +        if ((currentFile >= 0) ? (sounds[currentFile]->parser->isAnimatable) : false) {
No, this ternary is necessary because `sounds[currentFile]` crashes if `currentFile >= 0`.

2024-04-16 00:02 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +    if (playHead->getCurrentPosition(currentPositionInfo)) {
Done, PR coming soon. Sucks that they deprecated something so straightforward in favor of something so awfully overcomplicated lol

2024-04-16 00:06 UTC, DJLevel3 commented on Source/gpla/LineArtParser.cpp
Annoyingly, I had to make some slight changes at the beginning and the end to make everything work, which makes it hard to combine them without rewriting the functionality surrounding ObjectServer. I had to do this because ObjectServer used a single vector<unique_ptr(Shape)> which cannot itself be put into a vector because of how unique_ptrs work.

2024-04-16 00:08 UTC, DJLevel3 commented
I've made all the requested changes that I deem feasible for now, I still need to add some other functionality so this will remain a draft for the time being.

2024-04-16 00:31 UTC, DJLevel3 commented
Fixes #127

2024-04-16 00:32 UTC, DJLevel3 commented
Fixes #134

2024-04-16 06:41 UTC, jameshball commented on Source/PluginProcessor.cpp
> +        if ((currentFile >= 0) ? (sounds[currentFile]->parser->isAnimatable) : false) {
Because of [short circuiting](https://www.google.com/amp/s/www.geeksforgeeks.org/short-circuiting-in-c-and-linux/amp/) this shouldn't be an issue because sounds[currentFile] will only evaluate if currentFile >= 0

2024-04-17 15:03 UTC, DJLevel3 commented
I'm pretty sure this is release ready! I have made all the changes I intended to make and I have fixed some bugs that I found, so I'm marking this as ready for review!

2024-04-17 15:05 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +        if ((currentFile >= 0) ? (sounds[currentFile]->parser->isAnimatable) : false) {
I just tested that code and I got a crash on that line when building for debug but not release, so I'd say it's safer to leave it as is so there's no chance the compiler will mess something up.

2024-04-19 20:25 UTC, jameshball requested changes
Thanks again so much for all the changes! Sorry that the code review has gotten a bit stricter since the old osci-render days 😅 Keen to keep it easy to add new features :)

2024-04-19 20:25 UTC, jameshball commented on Source/LineArtComponent.cpp
> +			audioProcessor.animationRate = std::stof(rate.getText().toStdString());
Instead of doing a try catch for checking whether the input is a number, can you configure it in the same way as https://github.com/jameshball/osci-render/blob/main/Source/components/DoubleTextBox.h ? This is used here as an example https://github.com/jameshball/osci-render/blob/0615a46c5dc5aaf1a58db9d4dc119ae9c33cee5c/Source/components/AudioRecordingComponent.h#L262

You might need to make a separate class, or modify this class to support integers instead of doubles, but it should be mostly the same code but simpler to ignore decimal points and just care about digits.

2024-04-19 20:25 UTC, jameshball commented on Source/PluginProcessor.cpp
> +            currentPositionInfo = *cpi;
Can this be a local variable instead rather than a member?

2024-04-19 20:25 UTC, jameshball commented on Source/PluginProcessor.cpp
> +        if (animateLineArt && (sample % (int)(sampleRate / 200) == 0)) {
Can you explain why we have `(sample % (int)(sampleRate / 200) == 0)` I'm not sure I understand the purpose of it

2024-04-19 20:25 UTC, jameshball commented on Source/PluginProcessor.cpp
> +            if (syncMIDIAnimation) animationTime = playTimeBeats;
Please can you add curly braces to if statements for readability?

2024-04-19 20:25 UTC, jameshball commented on Source/PluginProcessor.cpp
> +    lineArtXml->setAttribute("animateLineArt", animateLineArt);
Instead of manually saving and loading to the project file, can you instead create parameters for all these variables? For boolean ones there are examples where these are added (and you can see how the values are initiated in the header file) here: https://github.com/jameshball/osci-render/blob/1f6523aded3d1df3217fea690ef09958b337c8bd/Source/PluginProcessor.cpp#L169

And for floats there are examples here: https://github.com/jameshball/osci-render/blob/1f6523aded3d1df3217fea690ef09958b337c8bd/Source/PluginProcessor.cpp#L182

Doing this means they will automatically save and load to projects, and they can be automated from a DAW :)

2024-04-19 20:25 UTC, jameshball commented on Source/PluginProcessor.h
> +            VERSION_HINT, 220.0, 0.0, 12000.0, 0.1
Why was this changed?

2024-04-19 20:25 UTC, jameshball commented on Source/PluginProcessor.h
> +    bool animateLineArt = false;
These can all be boolean/float/int parameters instead as mentioned above :)

2024-04-19 20:25 UTC, jameshball commented on Source/parser/FileParser.cpp
> +		if (gpla != nullptr) isAnimatable = true;
You can simplify this with:
```cpp
isAnimatable = gpla != nullptr;
```

2024-04-19 20:25 UTC, jameshball commented on Source/gpla/LineArtParser.cpp
Before we merge I'd still like to combine the logic from ObjectServer with this.

2024-04-19 20:30 UTC, DJLevel3 commented on Source/PluginProcessor.h
> +            VERSION_HINT, 220.0, 0.0, 12000.0, 0.1
440 Hertz my ears (lol) when I forget to change it before opening a file for testing, I changed it to make testing easier and forgot to change it back before pushing changes

2024-04-19 20:31 UTC, jameshball commented on Source/PluginProcessor.h
> +            VERSION_HINT, 220.0, 0.0, 12000.0, 0.1
Do you think it should stay at 220? Might be a good option tbh, it is kinda high pitch

2024-04-19 20:31 UTC, DJLevel3 commented on Source/parser/FileParser.cpp
> +		if (gpla != nullptr) isAnimatable = true;
I genuinely didn't think of doing that! I'll update it.

2024-04-19 20:32 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +            if (syncMIDIAnimation) animationTime = playTimeBeats;
Sure! I do this to make the code smaller when only 1 line is required, I'll go through and fix these as I find them

2024-04-19 20:34 UTC, DJLevel3 commented on Source/PluginProcessor.h
> +            VERSION_HINT, 220.0, 0.0, 12000.0, 0.1
Yeah, I'd even go to 110 but some really crappy speakers don't like frequencies that low so 220 is a safe bet

2024-04-21 17:10 UTC, DJLevel3 commented on Source/LineArtComponent.cpp
> +			audioProcessor.animationRate = std::stof(rate.getText().toStdString());
It was pretty much drop-in, as I was using floats anyway! I just need to make a few tweaks and it'll be good!

2024-04-21 17:11 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +            currentPositionInfo = *cpi;
Yep, I had it as a member for some other functionality I ended up deleting. Fixing now.

2024-04-21 17:17 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +    lineArtXml->setAttribute("animateLineArt", animateLineArt);
Done!

2024-04-21 17:17 UTC, DJLevel3 commented on Source/PluginProcessor.h
> +    bool animateLineArt = false;
Fixed!

2024-04-21 17:37 UTC, DJLevel3 commented on Source/gpla/LineArtParser.cpp
Done!

2024-04-21 17:39 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +        if (animateLineArt && (sample % (int)(sampleRate / 200) == 0)) {
I put that there because of a performance issue that I believe I have now resolved, I'll comment it out but leave it there just in case for now

2024-04-21 18:07 UTC, DJLevel3 commented on Source/LineArtComponent.cpp
> +			audioProcessor.animationRate = std::stof(rate.getText().toStdString());
Done!

2024-04-21 18:07 UTC, DJLevel3 commented on Source/PluginProcessor.cpp
> +        if (animateLineArt && (sample % (int)(sampleRate / 200) == 0)) {
No major hit to performance so far!

2024-04-24 19:33 UTC, DJLevel3 commented
Hmm, Codacy is failing it for issues that I don't think are actually issues. It seems that it hasn't realized that the "HIDDEN" does actually do something properly when running in Blender, and that "*.gpla" is the file extension.

2024-04-26 20:41 UTC, jameshball requested changes
Thanks again!! I've fixed a few bugs with it - please can you do the following last few changes:

- [x] Change any variable names/strings/ids etc. for MIDI sync to BPM sync (as discussed on Discord)
- [x] Update the name of 'framerate' to:
  - 'Frames per second' when BPM sync is disabled
  - 'Frames per beat' when BPM sync is enabled
- [ ] Add tooltips to Animate, BPM Sync, FPS/FPB, and Offset labels/buttons to explain what they do
  - There are plenty of examples of how to do this in the codebase, but reach out if you need help!
- [ ] Do a final test
  - Particularly to make sure that the original Blender implementation is still working fine
  - Also to make sure that there is no weird behaviour around line saving that you spotted before
  - Test both standalone and VST

2024-04-27 21:45 UTC, DJLevel3 reviewed
All looks pretty good except for this one strange extra modulo that doesn't appear to be necessary. I'll compile and test momentarily.

2024-04-27 21:45 UTC, DJLevel3 commented on Source/gpla/LineArtParser.cpp
> +    frameNumber = (numFrames + (fNum % numFrames)) % numFrames;
Why is this necessary? The modulo operator should always return a positive or zero result, so this code is redundant.

2024-04-27 22:31 UTC, DJLevel3 commented on Source/gpla/LineArtParser.cpp
> +    frameNumber = (numFrames + (fNum % numFrames)) % numFrames;
I reverted the change in the latest commit, so this is now fixed.

2024-04-27 22:33 UTC, DJLevel3 commented
All works as expected, but I'm going to change one thing that causes unexpected behavior: I'm going to change the fallback BPM to 60 so that ticking the BPM sync box in the standalone doesn't double the speed of the animation.

2024-04-27 22:37 UTC, DJLevel3 commented
Oops I have to test one more thing, 1 sec

2024-04-27 22:38 UTC, DJLevel3 commented
The line art's strange behavior is also not occurring, so I think all is good!

2024-04-28 21:11 UTC, jameshball approved these changes
All good to go! Just needs a little bit of documentation and we're good to release :)

2024-04-28 21:11 UTC, merged